name: Angular Build
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
      - name: Install Angular Dependencies
        run: npm install
      - name: Build Angular Application
        run: npm run build --prod
      - name: Upload App Files
        uses: actions/upload-artifact@v7
        with:
          name: app
          path: |
            **/dist/unit-economy-calc/
          if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: '${{ steps.deployment.outputs.page_url }}'
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: app
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
